# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
      with:
        version: # tutaj wstaw odpowiednią wersję, jeśli chcesz określić
        virtualenvs-create: true  # lub false, w zależności od potrzeb
        virtualenvs-in-project: false  # lub true, w zależności od potrzeb
        virtualenvs-path: # tutaj wstaw odpowiednią ścieżkę, jeśli chcesz określić
        installer-parallel: true  # lub false, w zależności od potrzeb
        installation-arguments: # tutaj wstaw dodatkowe argumenty instalacji, jeśli są potrzebne

    - name: Install dependencies
      run: |
        poetry install --no-root
